// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PruebaTecnica2025.Data;

#nullable disable

namespace PruebaTecnica2025.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PruebaTecnica2025.Models.Publication", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Ambientes")
                        .HasColumnType("integer")
                        .HasColumnName("Ambientes");

                    b.Property<int>("Antiguedad")
                        .HasColumnType("integer")
                        .HasColumnName("Antiguedad");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Descripcion");

                    b.Property<decimal>("Lat")
                        .HasColumnType("numeric")
                        .HasColumnName("Lat");

                    b.Property<decimal>("Lng")
                        .HasColumnType("numeric")
                        .HasColumnName("Lng");

                    b.Property<int>("M2")
                        .HasColumnType("integer")
                        .HasColumnName("M2");

                    b.Property<string>("TipoOperacion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("TipoOperacion");

                    b.Property<string>("TipoPropiedad")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("TipoPropiedad");

                    b.HasKey("Id");

                    b.ToTable("Publications", (string)null);
                });

            modelBuilder.Entity("PruebaTecnica2025.Models.PublicationImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("PublicationId")
                        .HasColumnType("integer")
                        .HasColumnName("PublicationId");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Url");

                    b.HasKey("Id");

                    b.HasIndex("PublicationId");

                    b.ToTable("PublicationImages", (string)null);
                });

            modelBuilder.Entity("PruebaTecnica2025.Models.PublicationImage", b =>
                {
                    b.HasOne("PruebaTecnica2025.Models.Publication", "Publication")
                        .WithMany("Imagenes")
                        .HasForeignKey("PublicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Publication");
                });

            modelBuilder.Entity("PruebaTecnica2025.Models.Publication", b =>
                {
                    b.Navigation("Imagenes");
                });
#pragma warning restore 612, 618
        }
    }
}
